displayName=Overhead Additions
author=Yenof, Ava
description=Displays GIM, clan, and friends chat overhead.
tags=overhead, chat, gim, group, cc, fc, group, over, head, text
version=1.0
plugins=com.overheadadditions.OverheadAdditions
build=standard